export const cvData = [
	{
		id: "originate",
		companyName: "Originate",
		companyPageUrl: "https://www.originate.com",
		position: "Software Engineer",
		location: "Aguascalientes, MX (Remote)",
		startDate: { month: "June", year: "2021" },
		endDate: { month: "", year: "" },
		descriptionBullets: [
			[
				"Development, design, and testing, as well as pure discussion or advisement of clients of customs or packaged software products, with the use of tools like ",
				"**Next.js**",
				", ",
				"**Nest.js**",
				", ",
				"**GraphQL**",
				", multiple ",
				"**AWS services**",
				" and ",
				"**PostgreSQL**",
				".",
			],
			[
				"Interfaced with UX/UI designers and other developers to build new interfaces and ensure the achievement of desired user interaction with overall applications via tools like ",
				"**Figma**",
				" or ",
				"**Adobe XD**",
				".",
			],
			[
				"Contributed to the architecture of projects which involved third party APIs consumption and event queueing / reaction, mainly with the use of diverse ",
				"**AWS services**",
				" such as ",
				"**SQS**",
				", ",
				"**Lambda**",
				" or ",
				"**Event Bridge**",
				".",
			],
		],
	},
	{
		id: "quintech",
		companyName: "QuinTech México",
		companyPageUrl: "https://www.quintech.mx",
		position: "Full Stack Developer",
		location: "Aguascalientes, MX",
		startDate: { month: "June", year: "2020" },
		endDate: { month: "October", year: "2021" },
		descriptionBullets: [
			[
				"Designed and developed interactive and responsive web applications for a variety of clients with the use of tools like ",
				"**React**",
				", ",
				"**Node.js**",
				", ",
				"**Express.js**",
				" and ",
				"**SQL**",
				".",
			],
			[
				"Interfaced with clients on a weekly basis, providing technological expertise.",
			],
			[
				"Architected & managed high scale projects with a team of up to 5 developers.",
			],
			[
				"Interfaced with user experience designers and other developers to ensure thoughtful and coherent user experiences across diverse web applications via tools like ",
				"**Sketch**",
				" or ",
				"**Figma**",
				".",
			],
			[
				"Proposed and implemented scalable solutions to issues identified with real-time data applications and complex interfaces rendering.",
			],
			[
				"Designed and developed multiple identity websites using ",
				"**React**",
				" and ",
				"**Gatsby**",
				".",
			],
			[
				"Developed and shipped highly interactive web applications with the use of tools such as ",
				"**Angular**",
				", ",
				"**Spring**",
				", ",
				"**Django**",
				" and ",
				"**MongoDB**",
				" or ",
				"**Google's Firebase**",
				".",
			],
		],
	},
	{
		id: "yellowpath",
		companyName: "Yellowpath Digital Branding",
		companyPageUrl: "https://www.yellowpath.mx",
		position: "Full Stack Developer",
		location: "Aguascalientes, MX",
		startDate: { month: "January", year: "2017" },
		endDate: { month: "June", year: "2020" },
		descriptionBullets: [
			[
				"Developed and shipped highly interactive web applications for diverse clients using ",
				"**React**",
				", ",
				"**Node.js**",
				" and ",
				"**Express.js**",
				".",
			],
			[
				"Architected and implemented high data management & analysis web applications using ",
				"**Angular**",
				", ",
				"**Django**",
				", ",
				"**Spring**",
				" and ",
				"**PHP**",
				".",
			],
			[
				"Modeled and managed databases & consumption methods & ",
				"**APIs**",
				" for diverse data sources such as ",
				"**PostgreSQL**",
				", ",
				"**MySQL**",
				", ",
				"**MongoDB**",
				" with tools such as ",
				"**GraphQL**",
				" or ",
				"**REST/RESTful APIs**",
				".",
			],
			[
				"Built and managed highly scalable projects with diverse architectures in teams of up to 11 developers with diverse profiles.",
			],
			[
				"Developed and maintained code for in-house and client websites primarily using ",
				"**HTML**",
				", ",
				"**CSS**",
				", ",
				"**Sass**",
				", ",
				"**JavaScript**",
				" and ",
				"**jQuery**",
				".",
			],
		],
	},
]
