export const projectData = [
	{
		id: "kinesis-rehab",
		name: "Kinesis Rehab",
		description: "Lorem ipsum",
		category: "develop",
		tags: ["HTML", "JS", "Sass"],
		externalUrl: "https://www.rehabkinesis.com/",
		imageUrls: ["/images/portfolio/develop/kinesis-rehab/thumbnail.jpg"],
		accent: "#A5CCE9",
	},
	{
		id: "aag-locksmith",
		name: "AAG Locksmith",
		description: "Lorem ipsum",
		category: "develop",
		tags: ["HTML", "JS", "Sass"],
		externalUrl: "https://www.aagcarlockout.com/",
		imageUrls: ["/images/portfolio/develop/aag-locksmith/thumbnail.jpg"],
		accent: "#FEC101",
	},
	{
		id: "radio-universal",
		name: "Radio Universal",
		description: "Lorem ipsum",
		category: "develop",
		tags: ["HTML", "JS", "CSS"],
		externalUrl: "https://www.radiouniversal.mx/",
		imageUrls: ["/images/portfolio/develop/radio-universal/thumbnail.jpg"],
		accent: "#EEE",
	},
	{
		id: "la-serena",
		name: "La Serena",
		description: "Lorem ipsum",
		category: "develop",
		tags: ["HTML", "JS", "Sass"],
		externalUrl: "https://www.laserena.mx/",
		imageUrls: ["/images/portfolio/develop/la-serena/thumbnail.jpg"],
		accent: "#F1E8DF",
	},
	{
		id: "milla-83",
		name: "Milla 83",
		description: "Lorem ipsum",
		category: "develop",
		tags: ["HTML", "JS", "CSS", "PHP"],
		externalUrl: "https://www.milla83.com/",
		imageUrls: ["/images/portfolio/develop/milla-83/thumbnail.jpg"],
		accent: "#000",
	},
	{
		id: "medestore",
		name: "Medestore",
		description: "Lorem ipsum",
		category: "develop",
		tags: ["HTML", "JS", "CSS"],
		externalUrl: "https://www.medestore.mx/",
		imageUrls: ["/images/portfolio/develop/medestore/thumbnail.jpg"],
		accent: "#259BCF",
	},
	{
		id: "the-dive-machine",
		name: "The Dive Machine",
		description: "Lorem ipsum",
		category: "develop",
		tags: ["HTML", "JS", "Sass"],
		externalUrl: "https://www.thedivemachine.com/",
		imageUrls: ["/images/portfolio/develop/the-dive-machine/thumbnail.jpg"],
		accent: "linear-gradient(0deg, #0F1D2B 0%, #003762 100%)",
	},
	{
		id: "dashboard-monalisa",
		name: "Dashboard Monalisa",
		description: "Lorem ipsum",
		category: "develop",
		tags: ["HTML", "JS", "CSS", "PHP"],
		externalUrl: "https://www.andrevital.com/dashboard-monalisa",
		imageUrls: [
			"/images/portfolio/develop/dashboard-monalisa/thumbnail.jpg",
		],
		accent: "#E9399A",
	},
	{
		id: "cros-cupones",
		name: "Cros Cupones",
		description: "Lorem ipsum",
		category: "develop",
		tags: ["HTML", "JS", "CSS", "PHP"],
		externalUrl: "https://www.cros.com.mx/cupones",
		imageUrls: ["/images/portfolio/develop/cros-cupones/thumbnail.jpg"],
		accent: "#12224A",
	},
	{
		id: "dashboard-eventos",
		name: "Dashboard Eventos",
		description: "Lorem ipsum",
		category: "develop",
		tags: ["HTML", "CSS", "PHP"],
		externalUrl: "https://www.andrevital.com/dashboard-eventos",
		imageUrls: [
			"/images/portfolio/develop/dashboard-eventos/thumbnail.jpg",
		],
		accent: "#314471",
	},
	{
		id: "live-out-2015",
		name: "Live Out 2015",
		description: "Lorem ipsum",
		category: "photo",
		tags: ["Musical Photography"],
		imageUrls: ["/images/portfolio"],
		accent: "#007C27",
	},
	{
		id: "live-out-2016",
		name: "Live Out 2016",
		description: "Lorem ipsum",
		category: "photo",
		tags: ["Musical Photography"],
		imageUrls: ["/images/portfolio"],
		accent: "#000",
	},
]
