/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedQueryDocumentNode } from "graphql";
export type GetBlogPathsParams = {
    articles: ({
        data: ({
            attributes: ({
                slug: string;
            }) | null;
        })[];
    }) | null;
};
export type GetBlogPathsParamsVariables = {};
export type GetBlogPathsParamsDocument = TypedQueryDocumentNode<GetBlogPathsParams, GetBlogPathsParamsVariables>;
