/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedQueryDocumentNode } from "graphql";
export type GetPortfolioPathsParams = {
    projects: ({
        data: ({
            attributes: ({
                projectId: string;
                category: ("develop" | "photo") | null;
            }) | null;
        })[];
    }) | null;
};
export type GetPortfolioPathsParamsVariables = {};
export type GetPortfolioPathsParamsDocument = TypedQueryDocumentNode<GetPortfolioPathsParams, GetPortfolioPathsParamsVariables>;
