/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ArticleFields = {
    slug: string;
    title: string;
    content: string | null;
    tags: ({
        data: ({
            id: string | null;
            attributes: (TagFields) | null;
        })[];
    }) | null;
    thumbnail: ({
        data: ({
            attributes: ({
                image: {
                    data: ({
                        attributes: (MediaFields) | null;
                    }) | null;
                };
                authorName: string;
                authorLink: string;
                plaformName: string;
                platformLink: string;
                name: string;
            }) | null;
        }) | null;
    }) | null;
    createdAt: any | null;
};
export type TagFields = {
    tagId: string;
    value: string | null;
    category: ("develop" | "photo") | null;
};
export type MediaFields = {
    name: string;
    url: string;
    formats: any | null;
};
