/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type AssetFields = {
    assetId: number;
    assetSlug: string;
    artist: string | null;
    media: {
        data: ({
            attributes: (MediaFields) | null;
        }) | null;
    };
};
export type MediaFields = {
    name: string;
    url: string;
    formats: any | null;
};
