/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ProjectFields = {
    projectId: string;
    name: string;
    description: string;
    category: ("develop" | "photo") | null;
    tags: ({
        data: ({
            id: string | null;
            attributes: (TagFields) | null;
        })[];
    }) | null;
    externalUrl: string | null;
    galleryAssets: ({
        data: ({
            attributes: (AssetFields) | null;
        })[];
    }) | null;
    accentColor: string;
    logo: {
        data: ({
            attributes: (MediaFields) | null;
        }) | null;
    };
};
export type TagFields = {
    tagId: string;
    value: string | null;
    category: ("develop" | "photo") | null;
};
export type AssetFields = {
    assetId: number;
    assetSlug: string;
    artist: string | null;
    media: {
        data: ({
            attributes: (MediaFields) | null;
        }) | null;
    };
};
export type MediaFields = {
    name: string;
    url: string;
    formats: any | null;
};
