/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type TagFields = {
    tagId: string;
    value: string | null;
    category: ("develop" | "photo") | null;
};
