/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedQueryDocumentNode } from "graphql";
export type GetJobs = {
    jobs: ({
        data: ({
            id: string | null;
            attributes: ({
                jobId: string;
                companyName: string;
                companyPageUrl: string;
                position: string;
                location: string;
                startDate: {
                    month: string;
                    year: string;
                };
                endDate: ({
                    month: string;
                    year: string;
                }) | null;
                descriptionBullets: (({
                    id: string;
                    bullet: string;
                }) | null)[];
            }) | null;
        })[];
    }) | null;
};
export type GetJobsVariables = {};
export type GetJobsDocument = TypedQueryDocumentNode<GetJobs, GetJobsVariables>;
